// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/poker-themes/Midnight.tsx": () => import("../components/mockups/poker-themes/Midnight.tsx"),
  "./components/mockups/poker-themes/Monaco.tsx": () => import("../components/mockups/poker-themes/Monaco.tsx"),
  "./components/mockups/poker-themes/Obsidian.tsx": () => import("../components/mockups/poker-themes/Obsidian.tsx")
};
